abn_type_list:
- spikes
- contextual
- flip
- speedup
- noise
- cutoff
- scale
- wander
- average
dataset_path: Mononito/datasets
downsampling: 10
evaluation_metric: Best F-1
metric: influence
min_length: 256
model_architectures: all
n_jobs: 5
n_neighbors:
- 2
- 4
- 6
n_repeats: 2
n_splits: 100
n_validation_splits: 5
normalize: true
overwrite: true
random_seed: 13
results_path: Mononito/results
sliding_window: null
split: test
synthetic_ranking_criterion: f1
top_k: 3
top_kr: null
trained_model_path: Mononito/trained_models
training_size: 1
use_all_ranks: false
verbose: true
